### ISSUE TITLE
Crash when repeatedly clicking Get Departures.

### ISSUE THREAD

**Issue by kejsarn** [kejsarn/androidCourse#3]
I've gotten a crash when clicking Get Departures a few times in a row.

**Comment by kejsarn** [comment]
Got this:
`02-11 21:21:33.020 8475-8475/com.example.davidberg.androidkurs D/AndroidRuntime: Shutting down VM
02-11 21:21:33.020 8475-8475/com.example.davidberg.androidkurs E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                 Process: com.example.davidberg.androidkurs, PID: 8475
                                                                                 java.lang.NullPointerException: Attempt to read from field 'int android.support.v7.widget.RecyclerView$ItemAnimator$ItemHolderInfo.left' on a null object reference
                                                                                     at android.support.v7.widget.SimpleItemAnimator.animateChange(SimpleItemAnimator.java:130)
                                                                                     at android.support.v7.widget.RecyclerView.animateChange(RecyclerView.java:3062)
                                                                                     at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2924)
                                                                                     at android.support.v7.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:1445)
                                                                                     at android.support.v7.widget.RecyclerView.access$400(RecyclerView.java:144)
                                                                                     at android.support.v7.widget.RecyclerView$1.run(RecyclerView.java:282)
                                                                                     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                                                     at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                                     at android.view.Choreographer.doFrame(Choreographer.java:603)
                                                                                     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                                     at android.os.Handler.handleCallback(Handler.java:739)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                     at android.os.Looper.loop(Looper.java:148)
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
02-11 21:21:35.230 8475-8475/? I/Process: Sending signal. PID: 8475 SIG: 9
`
